#include <ft2build.h>
#include FT_FREETYPE_H

#include <cstdint>
#include <fstream>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

constexpr unsigned int kFirstCharacter = 32;
constexpr unsigned int kLastCharacter = 126;
constexpr int kPointSize = 9;
constexpr int kDpi = 96;

struct Glyph {
	std::uint16_t pixelOffset = 0;
	std::uint8_t width = 0;
	std::uint8_t height = 0;
	std::int8_t bearingLeft = 0;
	std::int8_t bearingTop = 0;
	std::uint8_t advance = 0;
};

int CeilPixels(FT_Pos value) {
	return static_cast<int>((value + 63) / 64);
}

bool FitsByte(int value) {
	return value >= 0 && value <= std::numeric_limits<std::uint8_t>::max();
}

bool FitsSignedByte(int value) {
	return value >= std::numeric_limits<std::int8_t>::min() &&
		value <= std::numeric_limits<std::int8_t>::max();
}

bool LoadGlyph(FT_Face face, unsigned int character, Glyph& output,
	std::vector<std::uint8_t>& pixels) {
	if (FT_Get_Char_Index(face, character) == 0) {
		std::cerr << "font has no glyph for ASCII " << character << '\n';
		return false;
	}
	const FT_Int32 flags = FT_LOAD_DEFAULT | FT_LOAD_MONOCHROME | FT_LOAD_TARGET_MONO;
	if (FT_Load_Char(face, character, flags) != 0 ||
		face->glyph->format != FT_GLYPH_FORMAT_BITMAP) {
		std::cerr << "font has no embedded bitmap strike for ASCII " << character << '\n';
		return false;
	}
	if (FT_Render_Glyph(face->glyph, FT_RENDER_MODE_MONO) != 0) {
		std::cerr << "FreeType could not load bitmap for ASCII " << character << '\n';
		return false;
	}

	const FT_GlyphSlot slot = face->glyph;
	const FT_Bitmap& bitmap = slot->bitmap;
	const int advance = static_cast<int>((slot->advance.x + 32) / 64);
	if (bitmap.pixel_mode != FT_PIXEL_MODE_MONO || !FitsByte(static_cast<int>(bitmap.width)) ||
		!FitsByte(static_cast<int>(bitmap.rows)) || !FitsSignedByte(slot->bitmap_left) ||
		!FitsSignedByte(slot->bitmap_top) || !FitsByte(advance) ||
		pixels.size() > std::numeric_limits<std::uint16_t>::max()) {
		std::cerr << "font glyph metrics exceed bitmap atlas limits for ASCII " << character << '\n';
		return false;
	}

	output.pixelOffset = static_cast<std::uint16_t>(pixels.size());
	output.width = static_cast<std::uint8_t>(bitmap.width);
	output.height = static_cast<std::uint8_t>(bitmap.rows);
	output.bearingLeft = static_cast<std::int8_t>(slot->bitmap_left);
	output.bearingTop = static_cast<std::int8_t>(slot->bitmap_top);
	output.advance = static_cast<std::uint8_t>(advance);
	if (bitmap.pixel_mode != FT_PIXEL_MODE_MONO) {
		std::cerr << "embedded bitmap strike is not monochrome for ASCII " << character << '\n';
		return false;
	}

	for (unsigned int rowIndex = 0; rowIndex < bitmap.rows; ++rowIndex) {
		const int pitch = bitmap.pitch;
		const unsigned int stride = static_cast<unsigned int>(pitch < 0 ? -pitch : pitch);
		const unsigned int sourceRow = pitch < 0 ? bitmap.rows - 1 - rowIndex : rowIndex;
		const unsigned char* row = bitmap.buffer + sourceRow * stride;
		for (unsigned int column = 0; column < bitmap.width; ++column) {
			const bool on = (row[column / 8] & (0x80u >> (column % 8))) != 0;
			pixels.push_back(on ? 255 : 0);
		}
	}
	return true;
}

void WriteHeader(const std::string& path, const std::vector<Glyph>& glyphs,
	const std::vector<std::uint8_t>& pixels, int ascent, int lineHeight) {
	std::ofstream output(path, std::ios::binary);
	if (!output) throw std::runtime_error("cannot create output header: " + path);
	output << "#pragma once\n\n"
		"// Generated by tools/generate_bitmap_font.cpp from Terminus (TTF) Medium.\n"
		"// 9pt at 96dpi, extracted from its embedded 12px monochrome bitmap strike.\n"
		"// Source TTF is intentionally not embedded or distributed.\n\n"
		"#include \"bitmap_font.h\"\n\n"
		"#include <array>\n\n"
		"namespace jpegview_linux {\n"
		"namespace {\n\n"
		"constexpr int kEmbeddedBitmapFontAscent = " << ascent << ";\n"
		"constexpr int kEmbeddedBitmapFontLineHeight = " << lineHeight << ";\n\n"
		"constexpr std::array<BitmapFontGlyph, " << glyphs.size() << "> kEmbeddedBitmapFontGlyphs = {{\n";
	for (const Glyph& glyph : glyphs) {
		output << "\t{" << glyph.pixelOffset << ", " << static_cast<int>(glyph.width) << ", "
			<< static_cast<int>(glyph.height) << ", " << static_cast<int>(glyph.bearingLeft) << ", "
			<< static_cast<int>(glyph.bearingTop) << ", " << static_cast<int>(glyph.advance) << "},\n";
	}
	output << "}};\n\nconstexpr std::array<std::uint8_t, " << pixels.size()
		<< "> kEmbeddedBitmapFontPixels = {{\n\t";
	for (std::size_t index = 0; index < pixels.size(); ++index) {
		output << static_cast<unsigned int>(pixels[index]);
		if (index + 1 != pixels.size()) output << ',';
		if ((index + 1) % 20 == 0 && index + 1 != pixels.size()) output << "\n\t";
		else if (index + 1 != pixels.size()) output << ' ';
	}
	output << "\n}};\n\n} // namespace\n} // namespace jpegview_linux\n";
	if (!output) throw std::runtime_error("failed while writing output header: " + path);
}

} // namespace

int main(int argc, char** argv) {
	if (argc != 3) {
		std::cerr << "usage: generate_bitmap_font <Terminus.ttf> <bitmap_font_data.h>\n";
		return 2;
	}

	FT_Library library = nullptr;
	FT_Face face = nullptr;
	if (FT_Init_FreeType(&library) != 0 || FT_New_Face(library, argv[1], 0, &face) != 0) {
		std::cerr << "FreeType could not open font: " << argv[1] << '\n';
		if (face != nullptr) FT_Done_Face(face);
		if (library != nullptr) FT_Done_FreeType(library);
		return 1;
	}
	if (FT_Set_Char_Size(face, 0, kPointSize * 64, kDpi, kDpi) != 0) {
		std::cerr << "FreeType could not set font size\n";
		FT_Done_Face(face);
		FT_Done_FreeType(library);
		return 1;
	}

	std::vector<Glyph> glyphs;
	std::vector<std::uint8_t> pixels;
	bool success = true;
	for (unsigned int character = kFirstCharacter; character <= kLastCharacter; ++character) {
		Glyph glyph;
		if (!LoadGlyph(face, character, glyph, pixels)) {
			success = false;
			break;
		}
		glyphs.push_back(glyph);
	}
	const int ascent = CeilPixels(face->size->metrics.ascender);
	const int lineHeight = CeilPixels(face->size->metrics.height);
	const std::string family = face->family_name == nullptr ? "unknown" : face->family_name;
	FT_Done_Face(face);
	FT_Done_FreeType(library);
	if (!success) return 1;
	if (family.find("Terminus") == std::string::npos) {
		std::cerr << "expected a Terminus font, got " << family << '\n';
		return 1;
	}

	try {
		WriteHeader(argv[2], glyphs, pixels, ascent, lineHeight);
	} catch (const std::exception& error) {
		std::cerr << error.what() << '\n';
		return 1;
	}
	std::cout << "Wrote " << glyphs.size() << " monochrome glyphs, " << pixels.size()
		<< " pixels, ascent " << ascent << ", line height " << lineHeight << '\n';
	return 0;
}
